name: Bug Report
description: File a bug report
title: "📦 "
labels: ["pr"]
assignees:
  - naviisml
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this pull request!
